apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  destination:
    name: ''
    namespace: cert-manager
    server: 'https://kubernetes.default.svc'
  source:
    path: bitnami/cert-manager
    repoURL: 'git@github.com:ehsansh84/helms.git'
    targetRevision: master
    helm:
      valueFiles:
        - values-iran.yaml
  project: public-charts
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
