---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik.greenrnd.com
  namespace: traefik
spec:
  dnsNames:
    - traefik.greenrnd.com
  secretName: traefik.greenrnd.com
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer