#apiVersion: traefik.containo.us/v1alpha1
#kind: IngressRoute
#metadata:
#  name: traefik-dashboard
#  namespace: default
#spec:
#  entryPoints:
#    - web
#  routes:
#  - kind: Rule
#    match: Host(`traefik.greenrnd.com`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
#    services:
#    - kind: TraefikService
#      name: api@internal
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard
  namespace: traefik
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`traefik.greenrnd.com`) # Hostname to match
      kind: Rule
      services: # Service to redirect requests to
        - name: api@internal # Special service created by Traefik pod
          kind: TraefikService
      middlewares:
        - name: auth
  tls:
    secretName: traefik.greenrnd.com
