service:
  type: NodePort
ports:
  web:
    nodePort: 32080
  websecure:
    nodePort: 32443
logs:
  general:
    level: ERROR
  access:
    # To enable access logs
    enabled: true
env:
  - name: TZ
    value: Asia/Tehran
image:
  pullPolicy: IfNotPresent
  name: registry.greenrnd.com/docker/docker/library/traefik
  tag: "2.5.4"
ingressRoute:
  dashboard:
    enabled: false # We will use a custom inrgessRoute with basic auth instead of the default one
securityContext:
  capabilities:
    drop: [ALL]
    add: [NET_BIND_SERVICE]
  readOnlyRootFilesystem: true
  runAsGroup: 0
  runAsNonRoot: false
  runAsUser: 0
