apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: argocd
  namespace: argocd
spec:
  entryPoints:
    - websecure
  routes:
    - match: >-
        HostSNI(`argo.doomain.ir`)
      services:
        - name: argocd-server
          namespace: argocd
          port: 443
  tls:
    passthrough: true
