apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor.greenrnd.com
  namespace: harbor
spec:
  dnsNames:
    - harbor.greenrnd.com
  secretName: harbor.greenrnd.com
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer