#---
#apiVersion: cert-manager.io/v1
#kind: ClusterIssuer
#metadata:
#  name: selfsigned
#spec:
#  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: h.greenrnd.com
  namespace: harbor
spec:
  dnsNames:
    - traefik.greenrnd.com
  secretName: h.greenrnd.com
  issuerRef:
    name: selfsigned
    kind: ClusterIssuer