externalURL: https://harbor.doomain.ir
expose:
  ingress:
    hosts:
      core: harbor.doomain.ir
      notary: notary.doomain.ir
  tls:
    enabled: false
#    certSource: secret
#    secret:
#      secretName: h.greenrnd.com-v787h


harborAdminPassword: Harbor@123
database:
  type: external
  external:
     host: "postgres-postgresql.postgres"
     port: "5432"
     username: "postgres"
     password: "ilQ7lUqd2B"
     coreDatabase: "registry"
     notaryServerDatabase: "notary_server"
     notarySignerDatabase: "notary_signer"

persistence:
  persistentVolumeClaim:
    registry:
     storageClass: "rook-ceph-block-2"
     size: 100Gi
    chartmuseum:
     storageClass: "rook-ceph-block-2"
    jobservice:
     storageClass: "rook-ceph-block-2"
    redis:
     storageClass: "rook-ceph-block-2"
    trivy:
     storageClass: "rook-ceph-block-2"
