externalURL: https://registry.greenrnd.com
imagePullPolicy: IfNotPresent
expose:
  ingress:
    hosts:
      core: registry.greenrnd.com
      notary: notary.greenrnd.com
  tls:
    enabled: true
    certSource: secret
    secret:
      secretName: greenrnd
      notarySecretName: greenrnd

harborAdminPassword: Harbor@123
database:
  type: external
  external:
     host: "postgres-postgresql.postgres"
     port: "5432"
     username: "postgres"
     password: "vt8kMtIvCS"
     coreDatabase: "registry"
     notaryServerDatabase: "notary_server"
     notarySignerDatabase: "notary_signer"

persistence:
  persistentVolumeClaim:
    registry:
     storageClass: "rook-ceph-block-2"
     size: 100Gi
    chartmuseum:
     storageClass: "rook-ceph-block-2"
    jobservice:
     storageClass: "rook-ceph-block-2"
    redis:
     storageClass: "rook-ceph-block-2"
    trivy:
     storageClass: "rook-ceph-block-2"
