apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: krakend
  namespace: krakend
spec:
  entryPoints:
    - websecure
  routes:
  - match: "krakend.greenrnd.com"
    kind: Rule
    services:
      - name: {{ $.Values.backend.name }}
        namespace: {{ .Values.metadata.namespace }}
        port: {{ .Values.backend.service.port }}
#  tls:
#    secretName: swapp-tls
#---
#apiVersion: traefik.containo.us/v1alpha1
#kind: IngressRoute
#metadata:
#  name: {{ .Values.backend.name }}-http
#  namespace: {{ .Values.metadata.namespace }}
#spec:
#  entryPoints:
#    - web
#  routes:
#  - match: Host({{ .Values.ingress.host | quote }})
##    middlewares:
##      - name: redirect-https
#    kind: Rule
#    services:
#      - name: {{ $.Values.backend.name }}
#        namespace: {{ .Values.metadata.namespace }}
#        port: {{ .Values.backend.service.port }}
