replication:
  enabled: true
  readReplicas: 3
primary:
  tolerations:
    - key: database
      operator: Exists
persistence:
  storageClass: "openebs-lvmpv"

readReplicas:
  tolerations:
    - key: database
      operator: Exists
initdbScriptsConfigMap: postrges-initdb-config
